name: Flutter CI

on:
  push:
    paths:
      - 'shop-flutter/**'
  pull_request:
    paths:
      - 'shop-flutter/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: flutter pub get
        working-directory: shop-flutter

      - name: Run analyzer
        run: flutter analyze
        working-directory: shop-flutter

      - name: Run tests
        run: flutter test
        working-directory: shop-flutter
