name: Admin React CI

on:
  push:
    paths:
      - 'shop-admin/**'
  pull_request:
    paths:
      - 'shop-admin/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: shop-admin

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: shop-admin

      - name: Build project
        run: npm run build
        working-directory: shop-admin
